### ISSUE TITLE
Can not use other selenium-version on windows

### ISSUE THREAD

**Issue by icaaq** [vvo/selenium-standalone#103]
If i do this on my windows
`selenium-standalone install --version=2.42.0`
i get this

```
Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.42/IEDriverServer_Win32_2.45.0.zip:
    at Request.<anonymous> (c:\stuff\nodist\bin\node_modules\selenium-standalone\lib\install.js:280:17)
    at Request.emit (events.js:95:17)
    at Request.onRequestResponse (c:\stuff\nodist\bin\node_modules\selenium-standalone\node_modules\request\request.js:1142:10)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1692:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1587:20)
    at TCP.onread (net.js:527:27)```

**Comment by vvo** [comment]
Try

```sh
selenium-standalone install --version=2.42.0 --drivers.ie.version=2.42.0
```

And close the issue if it fixes it @icaaq.

Thanks

**Comment by icaaq** [comment]
hmm, but if i only want to use chrome, why do I have to specify a ie driver?

**Comment by vvo** [comment]
I see I think the iedriver download path should default to the selenium one if not specified, do you think you can do a PR?

**Comment by vvo** [comment]
https://github.com/vvo/selenium-standalone/blob/master/lib/compute-download-urls.js

**Comment by icaaq** [comment]
Sure, I forked the repo this morning, coming up!

**Comment by vvo** [comment]
Fixed, new release incoming

**Comment by vvo** [comment]
see 4.6.0
