### ISSUE TITLE
Callback in selenium.start() called twice when process already exists

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#104]
Looks like the callback in `selenium.start()` is being called twice when Selenium's Java process already exists. I mean

```coffee
  selenium.start({spawnOptions: {stdio: 'ignore'}}, (err, seleniumProcess) ->
    console.log '<------------------ selenium started'
    if err
      cb(err)
    else
      # do something else
  )
```

To reproduce, make sure you already have the Selenium process running and then run the above: you will see that the console output is printed twice and an error is passed onto the callback on the first run.

The first error says something like:

```
[12:54:33] 'selenium' errored after 309 ms
[12:54:33] Error: Selenium exited before it could start
  at ChildProcess.errorIfNeverStarted (/home/michael-heuberger/Development/.../node_modules/selenium-standalone/lib/start.js:92:10)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
```

When the callback is called on the second time, error object is null and I have a `seleniumProcess` but it looks weird:

```
{ domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _closesNeeded: 1,
  _closesGot: 1,
  connected: false,
  signalCode: null,
  exitCode: 1,
  killed: false,
  spawnfile: '/usr/bin/java',
  _handle: null,
  spawnargs: 
   [ '/usr/bin/java',
     '-jar',
     '/home/michael-heuberger/Development/.../node_modules/selenium-standalone/.selenium/selenium-server/2.45.0-server.jar',
     '-Dwebdriver.chrome.driver=/home/michael-heuberger/Development/.../node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver' ],
  pid: 20472,
  stdin: null,
  stdout: null,
  stderr: null,
  stdio: [ null, null, null ] }
```

I expect just the error to be thrown and the callback not to be called again.

**Comment by vvo** [comment]
Could you try to open a pull request for this?

**Comment by binarykitchen** [comment]
Here you go https://github.com/vvo/selenium-standalone/pull/105

**Comment by dtothefp** [comment]
@binarykitchen @vvo I agree this is an issue but something like below works for me. Would be nice to have the error messages updated as @binarykitchen suggests

```js
import {join} from 'path';
import selenium from 'selenium-standalone';
import install from './install';

let babelPath = join(process.cwd(), 'gulp/config/babelhook');
const options = {
  desiredCapabilities: {
    browserName: 'chrome'
  }
};
var client = webdriverio.remote(options);

export default function(gulp, plugins, config) {
  var {mocha, gutil} = plugins;
  var {PluginError} = gutil;

  return (cb) => {
    install(() => {
      selenium.start({
        spawnOptions: {
          stdio: 'ignore'
        }
      }, (err, child) => {
        if(err) {
          throw new PluginError({
            plugin: '[selenium]',
            message:  `${err.message} => ps aux | grep selenium and kill process id`
          })
        }

        gulp.src([
          join(process.cwd(), 'test/*-selenium-spec.js')
        ])
        .pipe(mocha({
          timeout: 40000,
          require: [ babelPath ]
        }))
        .once('end', () => {
          child.kill();
          cb();
        });
      });
    });
  };
}

```

**Comment by davidangel** [comment]
I've confirmed that @binarykitchen's patch causes the below code to output `Error: Another Selenium process is already running`.

```
selenium = require('selenium-standalone');

gulp.task('selenium', function (done) {
    selenium.install({
        logger: function (message) { }
    }, function (err) {
        if (err) return done(err);

        selenium.start(function (err, child) {
            if (err) return done(err);
            selenium.child = child;
            done();
        });
    });
});
```

**Comment by vvo** [comment]
will release, thanks everyone and @binarykitchen for your patience

**Comment by binarykitchen** [comment]
hmm, somehow this update causes more problems: it seems that the callback is never fired when the main process exited.
