### ISSUE TITLE
selenium-standalone Chrome/Safari issues running on OSX

### ISSUE THREAD

**Issue by michaelBenin** [vvo/selenium-standalone#107]
Related: https://github.com/webdriverio/webdriverio/issues/577

Chrome: Version 43.0.2357.124 (64-bit)
Mac: 10.10.3
node: v0.12.4

**Comment by michaelBenin** [comment]
Also broken for safari, see: 

https://github.com/webdriverio/webdriverio/issues/579

**Comment by vvo** [comment]
@michaelBenin please provide a detailed issue explanation on the issue you are facing, right now I see babel/selenium issues rather than selenium standalone.

selenium standalone is only a launcher, if you have selenium/webdriver issues that's another problem.

**Comment by michaelBenin** [comment]
Hey @vvo, 

The issues I've been running into are working with selenium 2.4.5.

Since I've written this I've been able to get safari working by installing this extension:

http://selenium-release.storage.googleapis.com/2.45/SafariDriver.safariextz

Unfortunately google chrome is the only browser holding my team back.

I've tried using older versions / newer versions as well:

```
selenium-standalone install --version=2.46.0 --baseURL=http://selenium-release.storage.googleapis.com
selenium-standalone install --drivers.chrome.version=2.16 --drivers.chrome.baseURL=http://chromedriver.storage.googleapis.com
selenium-standalone start --version=2.46.0 --drivers.chrome.version=2.16 
```

I've also tried the previous versions as well. 

The programmatic api from the example:
http://twin.github.io/selenium-testing-workflow-with-webdriverio/

Is not working and just hangs in my gulp workflow. 

We have Firefox, Safari working great now. Would be great to get chrome working as well and then be able to fix the programmatic api instead of using the cli.

**Comment by vvo** [comment]
strange google chrome is not working, try to get the relevant selenium log maybe.

**Comment by michaelBenin** [comment]
Sure I'll do this with the default settings:

```
Admins-MacBook-Pro:~ mbenin$ selenium-standalone start
09:50:18.954 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
09:50:18.983 INFO - Java: Oracle Corporation 25.45-b02
09:50:18.983 INFO - OS: Mac OS X 10.10.3 x86_64
09:50:18.990 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
09:50:19.048 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: MAC
09:50:19.072 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
09:50:19.072 INFO - Version Jetty/5.1.x
09:50:19.073 INFO - Started HttpContext[/selenium-server,/selenium-server]
09:50:19.091 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@d7b1517
09:50:19.092 INFO - Started HttpContext[/wd,/wd]
09:50:19.092 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
09:50:19.092 INFO - Started HttpContext[/,/]
09:50:19.095 INFO - Started SocketListener on 0.0.0.0:4444
09:50:19.095 INFO - Started org.openqa.jetty.jetty.Server@7cd84586
Selenium started
09:50:25.913 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
09:50:25.920 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
Starting ChromeDriver 2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f) on port 34362
Only local connections are allowed.
09:50:46.107 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.92', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.92', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.92', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
	... 14 more
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
	at org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:74)
	at org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:165)
	at org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:183)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:170)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:62)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	... 19 more
09:50:46.114 WARN - Exception: The process has not exited yet therefore no result is available ...
```

**Comment by michaelBenin** [comment]
So I've done a lot of research and debugging on this, I've read that you need chromedriver on your path, but I've done that and still ran into the same issue.

For now this isn't so bad. As my team is all node developers and we are able to write our tests in firefox and safari then run them on chrome using sauce labs.

Hopefully we can get this working in chrome, and lockdown all deps (chromedriver, selenium, node version, npm deps with shrinkwrap, instructions on installing the safari extension) and I'll open source a simple boiler plate for writing and running these tests using mocha and babel.

**Comment by vvo** [comment]
I think this is linked to selenium rather than selenium standalone, try to use the regular selenium standalone http://www.seleniumhq.org/download/ and see if it works, I doubt so

**Comment by michaelBenin** [comment]
Tried that Friday, same results.

**Comment by michaelBenin** [comment]
What version of Selenium is stable that you recommend using?

**Comment by vvo** [comment]
The one the http://www.seleniumhq.org/download/ advise I guess 2.46.0

**Comment by michaelBenin** [comment]
Do we know what version last ran successfully with google chrome on mac?

**Comment by vvo** [comment]
@michaelBenin It runs on a mac but not on your machine, so try the regular selenium project wihtout using my module and see if it works. If it does not then it's a selenium issue maybe related to the way google chrome is installed.

**Comment by michaelBenin** [comment]
What version mac do you have?

**Comment by vvo** [comment]
2.45. Iam on linux

**Comment by michaelBenin** [comment]
Hey so I confirmed this is working on my mac osx yosemite (on a macbook air) but not on my macbook pro at work.

**Comment by michaelBenin** [comment]
@vvo any thoughts on what could be causing this?

**Comment by vvo** [comment]
No idea sorry we do not do anything special given the osx version, see selenium issues instead please this is not a selenium-standalone issue: https://code.google.com/p/selenium/issues/list

thx

**Comment by michaelBenin** [comment]
No prob. Sorry about all this.

**Comment by michaelBenin** [comment]
FYI issues are at https://github.com/SeleniumHQ/selenium/issues
