### ISSUE TITLE
Selenium Start Issues on Ubuntu 14.04 After Reboot

### ISSUE THREAD

**Issue by benmarten** [vvo/selenium-standalone#108]
I have installed selenium on AWS Ubuntu 14.04 image, installed jre, node (via nvm), and selenium-standalone. Everything works great until I reboot.

This is the console output:

	ubuntu@ip-172-31-******:~$ xvfb-run --server-args="-screen 0, 1366x768x24" selenium-standalone start
	12:43:12.599 INFO - Launching a standalone server
	Setting system property webdriver.chrome.driver to /home/ubuntu/.nvm/versions/node/v0.12.5/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
	12:43:12.635 INFO - Java: Oracle Corporation 24.79-b02
	12:43:12.635 INFO - OS: Linux 3.13.0-55-generic amd64
	12:43:12.655 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
	12:43:12.775 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match with current platform: LINUX
	12:43:12.811 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
	12:43:12.812 INFO - Version Jetty/5.1.x
	12:43:12.813 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
	12:43:12.819 INFO - Started HttpContext[/selenium-server,/selenium-server]
	12:43:12.819 INFO - Started HttpContext[/,/]
	/home/ubuntu/.nvm/versions/node/v0.12.5/lib/node_modules/selenium-standalone/bin/selenium-standalone:54
	        throw err;
	              ^
	Error: Unable to connect to selenium
	    at hasStarted (/home/ubuntu/.nvm/versions/node/v0.12.5/lib/node_modules/selenium-standalone/lib/check-started.js:17:10)
	    at Timer.listOnTimeout (timers.js:119:15)
	ubuntu@ip-172-31-14-21:~$ sel12:44:30.510 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@26b77801
	12:44:30.510 INFO - Started HttpContext[/wd,/wd]
	12:44:30.514 INFO - Started SocketListener on 0.0.0.0:4444
	12:44:30.517 INFO - Started org.openqa.jetty.jetty.Server@440939dc

And this is the output after I start a selenium script with firefox:

                at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
                at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
                at java.util.concurrent.FutureTask.run(FutureTask.java:262)
                at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at java.lang.Thread.run(Thread.java:745)
        Caused by: java.lang.reflect.InvocationTargetException
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
                at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
                ... 9 more
        Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 

        (process:4715): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
        Error: cannot open display: :99

        (process:4723): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
        Error: cannot open display: :99

        Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
        System info: host: 'ip-172-31-14-21', ip: '172.31.14.21', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-55-generic', java.version: '1.7.0_79'
        Driver info: driver.version: FirefoxDriver
                at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
                at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
                at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
                at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
                at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
                at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
                ... 14 more
        Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

        (process:4715): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
        Error: cannot open display: :99

        (process:4723): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
        Error: cannot open display: :99

                at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
                ... 19 more
        12:47:31.196 WARN - Exception: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

        (process:4715): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
        Error: cannot open display: :99

        (process:4723): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
        Error: cannot open display: :99

Please note, that the setup worked fine until after the first reboot after installing selenium. Any help appreciated...

**Comment by vvo** [comment]
maybe a software upgrade broke selenium?

**Comment by vvo** [comment]
try to use selenium alone http://www.seleniumhq.org/download/ without selenium-standalone, and see if it works

**Comment by benmarten** [comment]
ok, i got it working again, happens always after reboot. i start it:
`xvfb-run --server-args="-screen 1, 1366x768x24" selenium-standalone start`
then stop it with ctrl+c
then `killall java` then start it again, and it seems to work... no idea why...

**Comment by vvo** [comment]
maybe you should wait a little bit for your server to be connected/online before starting the start script

start script has one minute to start then it fails. it checks that the selenium is ready by calling a url:
https://github.com/vvo/selenium-standalone/blob/master/lib/get-selenium-status-url.js
https://github.com/vvo/selenium-standalone/blob/master/lib/check-started.js
https://github.com/vvo/selenium-standalone/blob/master/lib/start.js#L80

**Comment by itaimalek** [comment]
Happens to me as well, trying to launch it via NPM:

`xvfb-run --server-args="-screen 0, 1366x768x24" selenium-standalone start`
 gave this as an error:
`selenium-standalone:56
        throw err;
        ^

Error: Unable to connect to selenium
    at hasStarted (<project path>/node_modules/selenium-standalone/lib/check-started.js:17:10)
    at Timer.listOnTimeout (timers.js:92:15)
`
