### ISSUE TITLE
"New random session seed" wont start

### ISSUE THREAD

**Issue by mbitson** [vvo/selenium-standalone#109]
Hey There!

While I'm sure this is more of an issue with my environment than the repo, I'm not really sure how to continue from here. I've installed your package and ran: 
```
xvfb-run --server-args="-screen 0, 1366x768x24" selenium-standalone start -- -debug
```

This gives me the following output (Well, the end of it at least):
```
15:48:40.905 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
15:48:40.906 DEBUG - add component: HttpContext[/wd,/wd]
15:48:40.906 DEBUG - Added HttpContext[/wd,/wd] for host *
15:48:40.906 DEBUG - Starting org.openqa.jetty.jetty.Server@440939dc
15:48:40.907 INFO - Version Jetty/5.1.x
15:48:40.908 DEBUG - LISTENERS: [SocketListener0@0.0.0.0:4444]
15:48:40.908 DEBUG - HANDLER: {null={/selenium-server/driver/*=[HttpContext[/selenium-server/driver,/selenium-server/driver]], /selenium-server/*=[HttpContext[/selenium-server,/selenium-server]], /=[HttpContext[/,/]], /wd/*=[HttpContext[/wd,/wd]]}}
15:48:40.909 DEBUG - Starting HttpContext[/selenium-server/driver,/selenium-server/driver]
15:48:40.909 DEBUG - Init classloader from null, sun.misc.Launcher$AppClassLoader@68e1ca74 for HttpContext[/selenium-server/driver,/selenium-server/driver]
15:48:40.909 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
15:48:40.910 DEBUG - Starting HttpContext[/selenium-server,/selenium-server]
15:48:40.910 DEBUG - Init classloader from null, sun.misc.Launcher$AppClassLoader@68e1ca74 for HttpContext[/selenium-server,/selenium-server]
15:48:40.911 DEBUG - Started org.openqa.jetty.http.handler.SecurityHandler in HttpContext[/selenium-server,/selenium-server]
15:48:40.911 DEBUG - Started org.openqa.selenium.server.StaticContentHandler in HttpContext[/selenium-server,/selenium-server]
15:48:40.911 DEBUG - Started org.openqa.selenium.server.SessionExtensionJsHandler in HttpContext[/selenium-server,/selenium-server]
15:48:40.911 DEBUG - Started org.openqa.selenium.server.htmlrunner.SingleTestSuiteResourceHandler in HttpContext[/selenium-server,/selenium-server]
15:48:40.911 DEBUG - Started org.openqa.selenium.server.SeleniumDriverResourceHandler in HttpContext[/selenium-server,/selenium-server]
15:48:40.911 INFO - Started HttpContext[/selenium-server,/selenium-server]
15:48:40.912 DEBUG - Starting HttpContext[/,/]
15:48:40.912 DEBUG - Init classloader from null, sun.misc.Launcher$AppClassLoader@68e1ca74 for HttpContext[/,/]
15:48:40.912 DEBUG - Started org.openqa.selenium.server.ProxyHandler in HttpContext[/,/]
15:48:40.912 INFO - Started HttpContext[/,/]
15:48:40.912 DEBUG - Starting HttpContext[/wd,/wd]
15:48:40.912 DEBUG - Init classloader from null, sun.misc.Launcher$AppClassLoader@68e1ca74 for HttpContext[/wd,/wd]
15:48:40.913 DEBUG - Starting org.openqa.jetty.jetty.servlet.ServletHandler@488f612f
15:48:40.913 DEBUG - New random session seed

/usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:54
        throw err;
              ^
Error: Unable to connect to selenium
    at hasStarted (/usr/local/lib/node_modules/selenium-standalone/lib/check-started.js:17:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

Any input on how I could begin to debug this would be greatly appreciated. I've checked for logs and cant find any that contain anything relevant. 

Thanks for your time!

**Comment by vvo** [comment]
The unable to connect to selenium comes from lib/check-started.js:17:10 in this repo, could you have a look to see what's wrong?

Basically this will do a GET on the computed url for your selenium instance.

It's pretty straightforward to add a simple console.log() to see what's the computed url and see why the GET doesn't works.

That would help us a lot @mbitson thanks

**Comment by mbitson** [comment]
Hey vvo,

Firstly- I want to apologize for opening an issue in your repo where the problem is clearly my personal setup and not the repo. I'm hoping that if nothing else, this shows some of the basic problems one might encounter when installing this standalone...

I added the console.log and went about it again- but it seems that rebooting between then and now has allowed me to continue one step further. The "New Random Session Seed" line continues without that error, but now after the selenium server starts, when I create a new session I receive the following error:

```
root@go:~# export DISPLAY=:10 && xvfb-run --server-args="-screen 10, 1024x768x24" selenium-standalone start -- -debug
09:00:54.208 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
09:00:54.260 INFO - Java: Oracle Corporation 24.79-b02
09:00:54.261 INFO - OS: Linux 3.13.0-52-generic amd64
09:00:54.290 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
09:00:54.290 INFO - Selenium server running in debug mode.
09:00:54.340 DEBUG - add component: SocketListener0@0.0.0.0:4444
09:00:54.358 DEBUG - add component: org.openqa.jetty.http.ResourceCache@3796a671
09:00:54.362 DEBUG - add component: org.openqa.selenium.server.ProxyHandler in HttpContext[/,/]
09:00:54.362 DEBUG - add component: HttpContext[/,/]
09:00:54.364 DEBUG - Added HttpContext[/,/] for host *
09:00:54.364 DEBUG - add component: org.openqa.jetty.http.ResourceCache@4032a615
09:00:54.366 DEBUG - added SC{BASIC,null,user,CONFIDENTIAL} at /org/openqa/selenium/tests/html/basicAuth/*
09:00:54.375 DEBUG - add component: org.openqa.jetty.http.handler.SecurityHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.381 DEBUG - add component: org.openqa.selenium.server.StaticContentHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.383 DEBUG - add component: org.openqa.selenium.server.SessionExtensionJsHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.384 DEBUG - add component: org.openqa.selenium.server.htmlrunner.SingleTestSuiteResourceHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.385 DEBUG - add component: org.openqa.selenium.server.htmlrunner.SeleniumHTMLRunnerResultsHandler@578cad92
09:00:54.385 DEBUG - add component: HttpContext[/selenium-server,/selenium-server]
09:00:54.386 DEBUG - Added HttpContext[/selenium-server,/selenium-server] for host *
09:00:54.462 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match with current platform: LINUX
09:00:54.492 DEBUG - add component: org.openqa.jetty.http.ResourceCache@157844d3
09:00:54.513 DEBUG - add component: org.openqa.selenium.server.SeleniumDriverResourceHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.513 DEBUG - add component: HttpContext[/selenium-server/driver,/selenium-server/driver]
09:00:54.514 DEBUG - Added HttpContext[/selenium-server/driver,/selenium-server/driver] for host *
09:00:54.514 DEBUG - add component: org.openqa.jetty.http.ResourceCache@65c44935
09:00:54.542 DEBUG - add component: WebDriver remote server
Selenium started
09:00:54.556 DEBUG - add component: org.openqa.jetty.jetty.servlet.HashSessionManager@5f936fc6
09:00:54.556 DEBUG - add component: org.openqa.jetty.jetty.servlet.ServletHandler@488f612f
09:00:54.563 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
09:00:54.563 DEBUG - add component: HttpContext[/wd,/wd]
09:00:54.564 DEBUG - Added HttpContext[/wd,/wd] for host *
09:00:54.564 DEBUG - Starting org.openqa.jetty.jetty.Server@440939dc
09:00:54.565 INFO - Version Jetty/5.1.x
09:00:54.565 DEBUG - LISTENERS: [SocketListener0@0.0.0.0:4444]
09:00:54.566 DEBUG - HANDLER: {null={/selenium-server/driver/*=[HttpContext[/selenium-server/driver,/selenium-server/driver]], /selenium-server/*=[HttpContext[/selenium-server,/selenium-server]], /=[HttpContext[/,/]], /wd/*=[HttpContext[/wd,/wd]]}}
09:00:54.566 DEBUG - Starting HttpContext[/selenium-server/driver,/selenium-server/driver]
09:00:54.567 DEBUG - Init classloader from null, sun.misc.Launcher$AppClassLoader@68e1ca74 for HttpContext[/selenium-server/driver,/selenium-server/driver]
09:00:54.567 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
09:00:54.567 DEBUG - Starting HttpContext[/selenium-server,/selenium-server]
09:00:54.567 DEBUG - Init classloader from null, sun.misc.Launcher$AppClassLoader@68e1ca74 for HttpContext[/selenium-server,/selenium-server]
09:00:54.568 DEBUG - Started org.openqa.jetty.http.handler.SecurityHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.568 DEBUG - Started org.openqa.selenium.server.StaticContentHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.569 DEBUG - Started org.openqa.selenium.server.SessionExtensionJsHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.569 DEBUG - Started org.openqa.selenium.server.htmlrunner.SingleTestSuiteResourceHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.569 DEBUG - Started org.openqa.selenium.server.SeleniumDriverResourceHandler in HttpContext[/selenium-server,/selenium-server]
09:00:54.569 INFO - Started HttpContext[/selenium-server,/selenium-server]
09:00:54.569 DEBUG - Starting HttpContext[/,/]
09:00:54.570 DEBUG - Init classloader from null, sun.misc.Launcher$AppClassLoader@68e1ca74 for HttpContext[/,/]
09:00:54.570 DEBUG - Started org.openqa.selenium.server.ProxyHandler in HttpContext[/,/]
09:00:54.570 INFO - Started HttpContext[/,/]
09:00:54.570 DEBUG - Starting HttpContext[/wd,/wd]
09:00:54.570 DEBUG - Init classloader from null, sun.misc.Launcher$AppClassLoader@68e1ca74 for HttpContext[/wd,/wd]
09:00:54.570 DEBUG - Starting org.openqa.jetty.jetty.servlet.ServletHandler@488f612f
09:00:54.571 DEBUG - New random session seed
jar:file:/usr/local/lib/node_modules/selenium-standalone/.selenium/selenium-server/2.45.0-server.jar!/sslSupport
09:01:36.052 INFO - Started SocketListener on 0.0.0.0:43282
09:02:50.752 INFO - Executing: [new session: Capabilities [{javascriptEnabled=true, browserName=firefox, takesScreenshot=true}]])
09:02:50.753 INFO - Creating a new session for Capabilities [{javascriptEnabled=true, browserName=firefox, takesScreenshot=true}]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

(process:31164): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Error: no display specified
```

In the above error you can see that the selenium server starts successfully but at 09:02:50 I connected to the selenium server and attempted to start a Firefox session and the server errored out.

It is possible that past attempts to install selenium may be conflicting with your standalone package. Unfortunately, I don't know enough about selenium and it's dependencies (obviously, as I'm attempting to use your standalone package) to fully uninstall all previous versions prior to using this standalone.

I appreciate your time and any input you can provide for me to get a bit further through this error.

Thank you!

**Comment by vvo** [comment]
From the first error message it does seems like a port problem, a firewall issue?

**Comment by vvo** [comment]
I advise you to search for the error message on google which already gives a lot of other people with this problem.

good luck

**Comment by raulsalamancaherrera** [comment]
I got same error in clean Ubuntu 14.04 and 16.04 installation. 

> 20:25:06.952 INFO - Launching a standalone Selenium Server
> Setting system property webdriver.chrome.driver to /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.22-x64-chromedriver
> Setting system property webdriver.gecko.driver to /usr/local/lib/node_modules/selenium-standalone/.selenium/geckodriver/0.9.0-x64-geckodriver
> 20:25:07.090 INFO - Java: Oracle Corporation 24.95-b01
> 20:25:07.090 INFO - OS: Linux 4.4.0-28-generic amd64
> 20:25:07.113 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
> 20:25:07.113 INFO - Selenium server running in debug mode.
> 20:25:07.377 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
> registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
> 20:25:07.378 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
> registration capabilities Capabilities [{platform=WINDOWS, browserName=MicrosoftEdge, version=}] does not match the current platform LINUX
> 20:25:07.379 INFO - Driver class not found: com.opera.core.systems.OperaDriver
> 20:25:07.380 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
> 20:25:07.382 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
> registration capabilities Capabilities [{platform=MAC, browserName=safari, version=}] does not match the current platform LINUX
> 20:25:07.385 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
> 20:25:07.385 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
> 
> /usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:61
>         throw err;
>               ^
> Error: Unable to connect to selenium
>     at hasStarted (/usr/local/lib/node_modules/selenium-standalone/lib/check-started.js:17:10)
>     at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by vvo** [comment]
The server did not start, try again using the standalone selenium server: http://www.seleniumhq.org/download/
