### ISSUE TITLE
ECONNRESET error on IE install

### ISSUE THREAD

**Issue by JulianLaval** [vvo/selenium-standalone#127]
I am attempting to install Polymer's `web-component-tester`, of which `selenium-standalone` is a dependency.

Upon reaching the IE Install step of the `selenium-standalone` installation, an ECONNRESET error is thrown, preventing me from correctly downloading `web-component-tester`. The error log is as follows:

```
----------
selenium-standalone installation starting
----------

---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
to: C:\Users\Julien\AppData\Roaming\npm\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\
selenium-server\2.47.1-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.18/chromedriver_win32.zip
to: C:\Users\Julien\AppData\Roaming\npm\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\
chromedriver\2.18-x64-chromedriver
---
ie install:
from: http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.47.0.zip
to: C:\Users\Julien\AppData\Roaming\npm\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\
iedriver\2.47.0-x64-IEDriverServer.exe
Failed to download selenium and/or chromedriver: [Error: Could not download http://selenium-release.storage.googleapis.com/2.47/selenium-ser
ver-standalone-2.47.1.jar: Error: read ECONNRESET]
selenium-standalone will attempt to re-download next time it is run.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
npm WARN optional dep failed, continuing wct-local@1.6.0
```

My `proxy` and `https-proxy` settings in `.npmrc` are set to `null`, if that's relevant.

Any ideas on how to solve this? Thanks!

**Comment by vvo** [comment]
What's your OS?

**Comment by JulianLaval** [comment]
Upon further inspection, it did indeed happen to be a proxy issue, solved by adding it to the environment variables rather than to `.npmrc`:

```
export http_proxy=<proxy_url>
export https_proxy=<proxy_url>
export HTTP_PROXY=<proxy_url>
export HTTPS_PROXY=<proxy_url>
```

Issue closed!

**Comment by vvo** [comment]
Ah yes I do not use .npmrc. Only npm does.
