### ISSUE TITLE
`Another Selenium process is already running` not necessarily an accurate message 

### ISSUE THREAD

**Issue by chadian** [vvo/selenium-standalone#170]
First off, thanks for this project and your work, it really helps get selenium off the ground.

I noticed that I was getting this error:
`Error: Another Selenium process is already running`

Even when I had never been able to get it working prior, so I wasn't sure how there could have been a process running.

I notice that this project is checking for an exit code of `1` which is an uncaught fatal exception from node's docs, and that the error likely didn't apply to my issue.

I did a `console.log(arguments)` within a `spawnCb` and looked at the process arguments that were being setup. Copying the pieces (java binary, `-jar`, other arguments) and running what was being executed on the command-line I got the error that my java version on El Capitan was too old. I updated this with `brew cask install java`, and all was good.

Maybe the error could suggest that a possible reason is that the process is already running and/or providing a way of providing the error's output directly?

**Comment by vvo** [comment]
Yes indeed that would be a lot better, may we could show the error as you said along with checking the error code. Would you want to try to have a PR at it? thanks it would help

**Comment by chadian** [comment]
Sure, I'll give it a shot!

**Comment by djom20** [comment]
I have the same error.

10:51:37.031 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver
10:51:37.071 INFO - Java: Oracle Corporation 25.74-b02
10:51:37.072 INFO - OS: Mac OS X 10.11.3 x86_64
10:51:37.083 INFO - v2.53.0, with Core v2.53.0. Built from revision 35ae25b
10:51:37.160 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
10:51:37.160 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
10:51:37.161 INFO - Driver class not found: com.opera.core.systems.OperaDriver
10:51:37.161 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
10:51:37.163 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
10:51:37.163 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
10:51:37.249 WARN - Failed to start: SocketListener0@0.0.0.0:4444

-------------------------------
Running as a standalone server:
-------------------------------

Usage: java -jar selenium-server.jar [-interactive] [options]

  -port <nnnn>: the port number the selenium server should use
    (default 4444)
  -timeout <nnnn>: an integer number of seconds we should allow a
    client to be idle
  -browserTimeout <nnnn>: an integer number of seconds a browser is
    allowed to hang
  -interactive: puts you into interactive mode.  See the tutorial for
    more details
  -singleWindow: puts you into a mode where the test web site
    executes in a frame. This mode should only be selected if the
    application under test does not use frames.
  -profilesLocation: Specifies the directory that holds the profiles
    that java clients can use to start up selenium.  Currently
    supported for Firefox only.
  -forcedBrowserMode <browser>: sets the browser mode to a single
    argument (e.g. "*iexplore") for all sessions, no matter what is
    passed to getNewBrowserSession
  -forcedBrowserModeRestOfLine <browser>: sets the browser mode to
    all the remaining tokens on the line (e.g. "*custom
    /some/random/place/iexplore.exe") for all sessions, no matter what
    is passed to getNewBrowserSession
  -userExtensions <file>: indicates a JavaScript file that will be
    loaded into selenium
  -browserSessionReuse: stops re-initialization and spawning of the
    browser between tests
  -avoidProxy: By default, we proxy every browser request; set this
    flag to make the browser use our proxy only for URLs containing
    '/selenium-server'
  -firefoxProfileTemplate <dir>: normally, we generate a fresh empty
    Firefox profile every time we launch.  You can specify a directory
    to make us copy your profile directory instead.
  -debug: puts you into debug mode, with more trace information and
    diagnostics on the console
  -browserSideLog: enables logging on the browser side; logging
    messages will be transmitted to the server.  This can affect
    performance.
  -ensureCleanSession: If the browser does not have user profiles,
    make sure every new session has no artifacts from previous
    sessions.  For example, enabling this option will cause all user
    cookies to be archived before launching IE, and restored after IE
    is closed.
  -trustAllSSLCertificates: Forces the Selenium proxy to trust all
    SSL certificates.  This doesn't work in browsers that don't use the
    Selenium proxy.
  -log <logFileName>: writes lots of debug information out to a log
    file and disables logging to console
  -logLongForm: writes information out to console in long format (for
    debugging purpose)
  -htmlSuite <browser> <startURL> <suiteFile> <resultFile>: Run a
    single HTML Selenese (Selenium Core) suite and then exit
    immediately, using the specified browser (e.g. "*firefox") on the
    specified URL (e.g. "http://www.google.com").  You need to specify
    the absolute path to the HTML test suite as well as the path to the
    HTML results file we'll generate.
  -proxyInjectionMode: puts you into proxy injection mode, a mode
    where the selenium server acts as a proxy server for all content
    going to the test application.  Under this mode, multiple domains
    can be visited, and the following additional flags are supported:

    -dontInjectRegex <regex>: an optional regular expression that
      proxy injection mode can use to know when to bypss injection
    -userJsInjection <file>: specifies a JavaScript file which will
      then be injected into all pages
    -userContentTransformation <regex> <replacement>: a regular
      expression which is matched against all test HTML content; the
      second is a string which will replace matches.  These flags can
      be used any number of times.  A simple example of how this could
      be useful: if you add "-userContentTransformation https http"
      then all "https" strings in the HTML of the test application will
      be changed to be "http".

This synopsis lists options available in standalone role only. To
  get help on the options available for other roles run the server with
  -help option and the corresponding -role option value.
java.net.BindException: Selenium is already running on port 4444. Or some other service is.
	at org.openqa.selenium.server.SeleniumServer.start(SeleniumServer.java:509)
	at org.openqa.selenium.server.SeleniumServer.boot(SeleniumServer.java:321)
	at org.openqa.selenium.server.SeleniumServer.main(SeleniumServer.java:240)
	at org.openqa.grid.selenium.GridLauncher$1.launch(GridLauncher.java:58)
	at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:127)
/usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:61
        throw err;
        ^

Error: Selenium exited before it could start
    at ChildProcess.errorIfNeverStarted (/usr/local/lib/node_modules/selenium-standalone/lib/start.js:123:15)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by mgrybyk** [comment]
Closing due to inactivity
