### ISSUE TITLE
Could not download chromedriver_linux64.zip: Error: socket hang up

### ISSUE THREAD

**Issue by fang-lin** [vvo/selenium-standalone#176]
I use in Bamboo-CI anfd docker container, there is a error in follow:

```
14-Apr-2016 04:42:09    [04:42:09] 'install:selenium' errored after 26 s
14-Apr-2016 04:42:09    [04:42:09] Error: Could not download https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip: Error: socket hang up
14-Apr-2016 04:42:09        at Request.<anonymous> (/project/node_modules/selenium-standalone/lib/install.js:210:12)
14-Apr-2016 04:42:09        at Request.g (events.js:260:16)
14-Apr-2016 04:42:09        at emitOne (events.js:77:13)
14-Apr-2016 04:42:09        at Request.emit (events.js:169:7)
14-Apr-2016 04:42:09        at Request.onRequestError (/project/node_modules/selenium-standalone/node_modules/request/request.js:971:8)
14-Apr-2016 04:42:09        at emitOne (events.js:77:13)
14-Apr-2016 04:42:09        at ClientRequest.emit (events.js:169:7)
14-Apr-2016 04:42:09        at TLSSocket.socketErrorListener (_http_client.js:256:9)
14-Apr-2016 04:42:09        at emitOne (events.js:77:13)
14-Apr-2016 04:42:09        at TLSSocket.emit (events.js:169:7)
14-Apr-2016 04:42:09    [04:42:09] Finished 'test:unit-jsdom' after 27 s
```

**Comment by vvo** [comment]
The url https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip does work so there must be something else going on

**Comment by monolithed** [comment]
```
Error: Could not request headers from https://chromedriver.storage.googleapis.com/2.22/chromedriver_mac32.zip: Error: connect ETIMEDOUT 64.233.161.128:443
  at Request.<anonymous> (/node_modules/selenium-standalone/lib/install.js:397:8)
  at Request.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Request.emit (events.js:188:7)
  at Request.onRequestError (/node_modules/selenium-standalone/node_modules/request/request.js:971:8)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at TLSSocket.socketErrorListener (_http_client.js:308:9)
  at emitOne (events.js:96:13)
  at TLSSocket.emit (events.js:188:7)
  at emitErrorNT (net.js:1272:8)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

I have the same problem on `selenium-standalone start`.

**Comment by vvo** [comment]
Hi @monolithed maybe you are behind a proxy and you need to configure selenium standalone to use that proxy well? See https://github.com/vvo/selenium-standalone#example

**Comment by vvo** [comment]
Also maybe: https://github.com/vvo/selenium-standalone#error-unable-to-get-local-issuer-certificate

**Comment by monolithed** [comment]
@vvo, it happens sometimes, not every time
