### ISSUE TITLE
latest selenium-standalone doesn't install or run

### ISSUE THREAD

**Issue by hayesmaker** [vvo/selenium-standalone#179]
I started getting firefox errors with selenium standalone, so decided to update:

`npm install selenium-standalone@latest -g`

now when i try
`selenium-standalone install` or `selenium-standalone start` i get this error:

```
➜  ~ selenium-standalone install
module.js:329
    throw err;
    ^

Error: Cannot find module 'bl'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/selenium-standalone/node_modules/request/request.js:12:10)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
```

**Comment by stephenash** [comment]
What version of `node` and `npm` are you using?

```text
10:41:10 sel $ node -v
v4.4.4

10:41:15 sel $ npm -v
2.15.1

10:41:18 sel $ npm install selenium-standalone
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
selenium-standalone@5.1.0 node_modules/selenium-standalone
├── commander@2.6.0
├── progress@1.1.8
├── urijs@1.16.1
├── minimist@1.1.0
├── async@1.2.1
├── mkdirp@0.5.0 (minimist@0.0.8)
├── which@1.1.1 (is-absolute@0.1.7)
├── request@2.51.0 (tunnel-agent@0.4.3, forever-agent@0.5.2, aws-sign2@0.5.0, caseless@0.8.0, oauth-sign@0.5.0, stringstream@0.0.5, json-stringify-safe@5.0.1, mime-types@1.0.2, tough-cookie@2.2.2, qs@2.3.3, node-uuid@1.4.7, combined-stream@0.0.7, form-data@0.2.0, http-signature@0.10.1, bl@0.9.5, hawk@1.1.1)
├── unzip@0.1.11 (setimmediate@1.0.4, readable-stream@1.0.34, pullstream@0.4.1, match-stream@0.0.2, binary@0.3.0, fstream@0.1.31)
└── lodash@3.9.3

10:41:31 sel $ ./node_modules/selenium-standalone/bin/selenium-standalone install
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
to: /Users/sash/Desktop/sel/node_modules/selenium-standalone/.selenium/selenium-server/2.53.0-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip
to: /Users/sash/Desktop/sel/node_modules/selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver


selenium-standalone installation [=================== ] 96% 0.0s

-----
selenium-standalone installation finished
-----
```

**Comment by vvo** [comment]
You may have a broken node_modules, please try again

**Comment by Pavankumar95153** [comment]
Hi,
I'm getting the below error when I ran the following command $ ./node_modules/selenium-standalone/bin/selenium-standalone install. Currently I'm using node v12.13.0 and npm 6.12.0

not found: java
Usage: selenium-standalone action [options]

Please help me to fix the issue. I installed the selenium-standalone via globally.

**Comment by vvo** [comment]
You need to install java jdk, google it
