### ISSUE TITLE
Run server and test via Jenkins fails to connect to server

### ISSUE THREAD

**Issue by MikiDavid** [vvo/selenium-standalone#189]
Hi,

I'm not sure if this issue should be posted at this project or other WDIO project, so if I'm wrong with posting it here please forgive me :)

I recently started to use WDIO with mocha and Jenkins, but from some reason, when I'm running my Jenkins job, it fail to connect to server.

My Jenkins Job has the following build steps in it:

1. Execute Shell with the command:
> selenium-standalone start

2. Execute Windows batch command:
> npm install

3. Execute Windows batch command:
> npm test

My wdio.conf.js file has no configuration to a specific port \ hub \ path in it (Relying on to the default localhost:4444)

My test script also are not configured with a specific port.

When running the Jenkins job, I get the following at the console:

> ERROR: Couldn't connect to selenium server
> chrome
>     at new RuntimeError (C:\Users\QA_PC\Desktop\customWorkspace\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:115:12)
>     at Request._callback (C:\Users\QA_PC\Desktop\customWorkspace\node_modules\webdriverio\build\lib\utils\RequestHandler.js:264:37)
>     at self.callback (C:\Users\QA_PC\Desktop\customWorkspace\node_modules\request\request.js:373:22)
>     at emitOne (events.js:90:13)
>     at Request.emit (events.js:182:7)
>     at Request.onRequestError (C:\Users\QA_PC\Desktop\customWorkspace\node_modules\request\request.js:971:8)
>     at emitOne (events.js:90:13)
>     at ClientRequest.emit (events.js:182:7)
>     at Socket.socketErrorListener (_http_client.js:295:9)
>     at emitOne (events.js:90:13)
> ERROR: Couldn't connect to selenium server
> chrome
>     at new RuntimeError (C:\Users\QA_PC\Desktop\customWorkspace\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:115:12)
>     at Request._callback (C:\Users\QA_PC\Desktop\customWorkspace\node_modules\webdriverio\build\lib\utils\RequestHandler.js:264:37)
>     at self.callback (C:\Users\QA_PC\Desktop\customWorkspace\node_modules\request\request.js:373:22)
>     at emitOne (events.js:90:13)
>     at Request.emit (events.js:182:7)
>     at Request.onRequestError (C:\Users\QA_PC\Desktop\customWorkspace\node_modules\request\request.js:971:8)
>     at emitOne (events.js:90:13)
>     at ClientRequest.emit (events.js:182:7)
>     at Socket.socketErrorListener (_http_client.js:295:9)
>     at emitOne (events.js:90:13)

How can I run the server as a Build Step with Jenkins and also connect to it?

**Comment by vvo** [comment]
@MikiDavid If this works locally for you then there's an error in jenkins. Maybe the selenium server is not yet started when you try to run the tests (can take some time)

Maybe the selenium server failed to start (see the jenkins console for any error)

**Comment by MikiDavid** [comment]
OK,
Is there a way to wait for step to finish (Maybe with a returned value) before next step?

I tried [this](http://unix.stackexchange.com/questions/63648/how-to-send-many-commands-to-shell-and-wait-for-the-command-behind-ends) solution but its not working. (From some reason the selenium-standalone start commands working only with Execute Windows batch command and not with Execute shell).

**Comment by vvo** [comment]
@MikiDavid If you want to programmatically wait for the selenium server to start, you should use maybe https://github.com/webdriverio/wdio-selenium-standalone-service or just use the programmatic API of selenium-standalone.

You could also "wait" before starting tests after running selenium standalone in the background.

**Comment by kathar1223** [comment]
@MikiDavid , I used the same commands you used, 
selenium-standalone start
```
2018-06-04 20:37:26.747:INFO:osjshC.ROOT:qtp1286084959-14: org.openqa.selenium.remote.server.WebDriverServlet-10bbd20a: Initialising WebDriverServlet
20:37:26.793 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@2f5d9fe0
20:37:26.797 INFO - /status: Executing GET on /status (handler: Status)
Selenium started
```
But the next command in shell is not executed. because the selenium-standalone start is active. the execution flow is not coming to second command. i.e npm run test

Can you Please help me?

**Comment by vvo** [comment]
You should open a new terminal to run tests OR control how both commands are loaded but that's not a question for the current project nor is it related to selenium-standalone.

Go to StackOverflow and ask how to run two commands in parallel. Easiest is just to run them in different terminals or use the programmatic API: https://github.com/vvo/selenium-standalone#seleniumstartopts-cb

Example: https://github.com/vvo/selenium-standalone/blob/master/test/programmatic.js
