### ISSUE TITLE
geckodriver missing - 404

### ISSUE THREAD

**Issue by ityu** [vvo/selenium-standalone#191]
when I run 
```selenium-selenium install ```

I got this error
`Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.8.0/geckodriver-0.8.0-win32.zip`

I try download this file manually, but this package does not exist!

**Comment by vvo** [comment]
Just fixed

see https://github.com/mozilla/geckodriver/issues/120

**Comment by navinjoy** [comment]
Hi,

I am getting the similar error intermittently ...can you please check?

[11:18:05] Using gulpfile c:\data\workspace\AUT-CI-QBOClient-develop-QBO.Prod-SMOKE-WIN\gulpfile.js
[11:18:05] Starting 'drivers'...
inside Selenium Install
[11:18:27] 'drivers' errored after 23 s
[11:18:27] **Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-win64.zip**: Error: connect ETIMEDOUT 54.231.81.160:443
    at Request.<anonymous> (c:\data\workspace\AUT-CI-QBOClient-develop-QBO.Prod-SMOKE-WIN\node_modules\selenium-standalone\lib\install.js:425:8)
    at Request.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (c:\data\workspace\AUT-CI-QBOClient-develop-QBO.Prod-SMOKE-WIN\node_modules\selenium-standalone\node_modules\request\request.js:971:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)

**Comment by jucrouzet** [comment]
ETIMEDOUT 54.231.81.160:443 => You have a connectivity problem (maybe a missing proxy ?), not a selenium-standalone problem.

**Comment by navinjoy** [comment]
Clicking on the link does work fine, only when running the gulp task for selenium standalone install, I see this error. This is intermittent.
