### ISSUE TITLE
Arch is partially ignored on install

### ISSUE THREAD

**Issue by nkbt** [vvo/selenium-standalone#212]
Partially I mean - it is not ignored as download dest, but ignored in download source.

``` js
const drivers = {
  baseURL: 'https://selenium-release.storage.googleapis.com',
  version: '2.53.1',
  chrome: {
    version: '2.22',
    arch: 'linux64',
    baseURL: 'https://chromedriver.storage.googleapis.com'
  },
  firefox: {
    version: '0.9.0',
    arch: 'linux64',
    baseURL: 'https://github.com/mozilla/geckodriver/releases/download'
  }
};

  selenium.install({
    drivers,
    logger: message => console.log(message)
  }, onSeleniumInstalled);
```

``` sh
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
to: /Users/nkbt/nkbt/nightwatch-autorun/node_modules/selenium-standalone/.selenium/selenium-server/2.53.1-server.jar

---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.22/chromedriver_mac64.zip
to: /Users/nkbt/nkbt/nightwatch-autorun/node_modules/selenium-standalone/.selenium/chromedriver/2.22-linux64-chromedriver

---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-macos.tar.gz
to: /Users/nkbt/nkbt/nightwatch-autorun/node_modules/selenium-standalone/.selenium/geckodriver/0.9.0-linux64-geckodriver
Error: Could not request headers from https://chromedriver.storage.googleapis.com/2.22/chromedriver_mac64.zip: 
    at Request.<anonymous> (/Users/nkbt/nkbt/nightwatch-autorun/node_modules/selenium-standalone/lib/install.js:392:17)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/Users/nkbt/nkbt/nightwatch-autorun/node_modules/request/request.js:1255:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at TLSSocket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)
```

**Comment by vvo** [comment]
I am all in for a PR if you know how to fix this

**Comment by nkbt** [comment]
I'd definitely pr, but for next several weeks it's too much work on me, so my oss stuff is on hold for a moment =(. Will see how it goes after that

**Comment by vvo** [comment]
good luck @nkbt I hope to see you later on this repo!!

**Comment by mgrybyk** [comment]
Please try the latest version.

Feel free to re-open if the issue persists.

Thanks!
