### ISSUE TITLE
Could not request headers

### ISSUE THREAD

**Issue by geomolenaar** [vvo/selenium-standalone#243]
Hi,

Today I was trying to install selenium-standalone and got the following error message: 

```
---
selenium install:
from: https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
to: C:\Users\LDRDZV1\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\selenium-server\2.53.1-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
to: C:\Users\LDRDZV1\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\chromedriver\2.25-x64-chromedriver
---
ie install:
from: https://selenium-release.storage.googleapis.com/2.53/IEDriverServer_x64_2.53.1.zip
to: C:\Users\LDRDZV1\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\iedriver\2.53.1-x64-IEDriverServer.exe
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-win64.zip
to: C:\Users\LDRDZV1\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\geckodriver\0.10.0-x64-geckodriver
C:\Users\LDRDZV1\AppData\Roaming\npm\node_modules\selenium-standalone\bin\selenium-standalone:93
        throw err;
        ^

Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-win64.zip: Error: connect ETIMEDOU
T 192.30.253.113:443
    at Request.<anonymous> (C:\Users\LDRDZV1\AppData\Roaming\npm\node_modules\selenium-standalone\lib\install.js:425:8)
    at Request.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\LDRDZV1\AppData\Roaming\npm\node_modules\selenium-standalone\node_modules\request\request.js:971:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```

Most likely same issue as #242

**Comment by geomolenaar** [comment]
Was my proxy that blocked the request -_-'

closing issue
