### ISSUE TITLE
Error loading Gecko driver

### ISSUE THREAD

**Issue by joao-arvins** [vvo/selenium-standalone#292]
## Expected Behavior
Selenium-standalone should be able to find all drivers all install them

## Current Behavior
Fails when trying to install gecko drivers for firefox

## Steps to Reproduce

1.  Run it
2.  It will fail in the first step ("selenium-standalone installation starting")

## Logs
`[14:33:00] Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-win64.zip: Error: read ECONNRESET
    at Request.<anonymous> (E:\projects\projectA\node_modules\selenium-standalone\lib\install.js:455:8)
    at Request.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (E:\projects\projectA\node_modules\request\request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)`

## Your Environment
* Version used: 5.0 (also failed for v 6.5)
* Selenium-standalone is used on it's own but also called by gulp-webdriver
* Windows 10

**Comment by zenonhun** [comment]
Try to open the geckodriver from a browser: https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-win64.zip
It is redirected to a wrong url. 
Something is wrong with the github download links, 
Unfortunately I cannot configure the selenium-standalen not to install or use the firefox driver. 
Only way I found is to edit the default-config.js in the node_modules/selenium-standalone/libs folder.

**Comment by zenonhun** [comment]
Related?
https://github.com/vvo/selenium-standalone/issues/265

**Comment by joao-arvins** [comment]
Hi @zenonhun . Yes, you're right it's related to that issue.
The github download links are working fine again ... we can already run Selenium?

That was the first time it happened to us. Did someone faced the same in the past (apart from the one time reffered on [#265 ](https://github.com/vvo/selenium-standalone/issues/265))?

**Comment by presidenten** [comment]
We have the same problem when we try to run tests in our office where we have a corporate proxy.
The driver can be downloaded from a browser, but not when trying to run tests.
Is there an option to set proxy or even better, use the system set proxy?

```shell
Error: Could not download https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-macos.tar.gz: Error: tunneling socket could not be established, statusCode=403
    at Request.<anonymous> (/Users/jher00/kod/edge/agent/node_modules/selenium-standalone/lib/install.js:386:12)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/jher00/kod/edge/agent/node_modules/selenium-standalone/node_modules/request/request.js:845:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onConnect (/Users/jher00/kod/edge/agent/node_modules/selenium-standalone/node_modules/tunnel-agent/index.js:167:23)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
```

**Comment by vvo** [comment]
Maybe try to configure the proxy via HTTP(S)_PROXY env variables? That should work:

```sh
HTTP_PROXY=proxyurl nodejs command
```

https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables
