### ISSUE TITLE
isUpToDate() in install.js should not reach Internet all the time

### ISSUE THREAD

**Issue by attila123** [vvo/selenium-standalone#324]
## Expected Behavior
I would expect isUpToDate() in install.js to simply check the integrity of the already downloaded zip or jar files (e.g. chromedriver zip, selenium jar). To achieve this, hopefully there is some npm package which can test the integrity of a zip file (similarly to unzip -t in command line). Maybe the yauzl package which this project uses can do this, did not check.

## Current Behavior
Currently isUpToDate() in install.js always makes requests to the Internet, even though with the 'If-None-Match' header. This makes the build process dependent on Internet access all the time. I don't think this is a good 'pattern'. While this is usually not a problem, it is still an unnecessary dependency introduced (to access Internet). (There might be some Internet access problems, or DNS server issues, etc. at any time, etc. even though with low probability). Ideally, for a build process, I would like everything installed in a docker image, and the build process should not need any access to the Internet. The docker image would be updated seldom, when needed, of course that would require Internet access, but that is OK as it happens seldom.

## Steps to Reproduce
In our project, selenium-standalone's download function is invoked by wdio-selenium-standalone-service npm module, which is used by wdio itself.
I added some logging to install.js, and it turned out that the download() function in our install.js is invoked with the following opts (running on my machine):
```
{ urls: 
   { selenium: 'https://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.2.jar',
     chrome: 'https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip' },
  fsPaths: 
   { chrome: 
      { installPath: '/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/wdio-selenium-standalone-service/node_modules/selenium-standalone/.selenium/chromedriver/2.29-x64-chromedriver',
        downloadPath: '/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/wdio-selenium-standalone-service/node_modules/selenium-standalone/.selenium/chromedriver/2.29-x64-chromedriver.zip' },
     selenium: 
      { installPath: '/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/wdio-selenium-standalone-service/node_modules/selenium-standalone/.selenium/selenium-server/3.5.2-server.jar',
        downloadPath: '/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/wdio-selenium-standalone-service/node_modules/selenium-standalone/.selenium/selenium-server/3.5.2-server.jar' } } }
```
Add the following line to /etc/hosts (in Linux, hosts file may be in a different directory in other OS-es) to simulate a network outage:
127.0.0.1       chromedriver.storage.googleapis.com selenium-release.storage.googleapis.com

## Logs
This will result in an error something like this:
```
Error: Could not request headers from https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip: Error: connect ECONNREFUSED 127.0.0.1:443
    at Request.<anonymous> (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/wdio-selenium-standalone-service/node_modules/selenium-standalone/lib/install.js:544:8)
    at Request.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/wdio-selenium-standalone-service/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```
Looking at the code, it's the isUpToDate() function trying to access the Internet, even though all the files are already downloaded locally.

## Your Environment
* Version of `selenium-standalone` that you are using: 6.11.0
* Is there another tool calling `selenium-standalone` on your behalf: wdio-selenium-standalone-service
* System/platform: Linux
* Other details that might be important:

**Comment by zjh1943** [comment]
I have the same problem. 
When network is good, `selenium-stantalone` starts well.
When network is bad, I can't start `selenium-stantalone` . It shows:

```
Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-macos.tar.gz: Error: socket hang up
    at Request.<anonymous> (/Users/zjh/Project/ones/ones-ai-web/node_modules/selenium-standalone/lib/install.js:552:8)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/zjh/Project/ones/ones-ai-web/node_modules/selenium-standalone/node_modules/request/request.js:845:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at TLSSocket.emit (events.js:221:7)
```

I think there is no need to request the headers at every starting of `selenium-standalone`. Or at least i can turn it off in some config file.

**Comment by attila123** [comment]
wedriver-manager in its current form is unfortunately not suitable for offline use. Our build guys could not make it work even with internal (in company's internal network) repo mirrors somehow.
I am sorry to say, I consider webdriver-manager FUBER (unless you consider fixing other peoples' code in addition to your daily work fun) for real life use (it's more like an educational toy), so we got rid of it finally. Just make an internal repo mirror for selenium jar and chromedriver, etc. wget them when needed in the build process, unzip the chromedriver, then one java command can start up your selenium server as needed (you can look up the command when webdriver-manager is started with sg. like 'ps -ef | grep selenium' or in the Task Manager in Windows, I believe). In Linux you can use & to start in background (you can consider nohup if needed), redirect the std out and std err to a file, and there you go, on Windows I'm not sure (on Windows 10 there is some POSIX subsystem). Or probably the best is to run it in background  via js (Node.js). Sorry again for my strong opinion, I had a lot of unplanned frustration with webdriver-manager and protractor (it got stuck when chrome got stuck, I needed to write a complete monitoring script over it).

**Comment by zjh1943** [comment]
@attila123 Thank you, very much,  for your detailed explaining. I will start the standalone service by other way.

**Comment by vvo** [comment]
@attila123 Not sure to get why we speak about webdriver-manager here since this is the repository of selenium-standalone.

It seems also you have a proposed solution. I am not actively using this package, if you are, then you will have to fix this yourself and I will gladly merge a PR solving the issue as you mentioned in the description.
