### ISSUE TITLE
Selenium installs other drivers than in config

### ISSUE THREAD

**Issue by netmajor** [vvo/selenium-standalone#325]
## Expected Behavior
installing selenium and chromedriver

## Current Behavior
I am set in config that I want only install chrome driver, but in log i see that it tries to download others also

## Steps to Reproduce
I am executing command: selenium-standalone install  --config=./selenium.conf.js with config 
```
var selenium = require('selenium-standalone');
 
selenium.install({
  // check for more recent versions of selenium here:
  // https://selenium-release.storage.googleapis.com/index.html
  version: '3.0.1',
  baseURL: 'https://selenium-release.storage.googleapis.com',
  drivers: {
    chrome: {
      // check for more recent versions of chrome driver here:
      // https://chromedriver.storage.googleapis.com/index.html
      version: '2.33',
      arch: process.arch,
      baseURL: 'https://chromedriver.storage.googleapis.com'
    },
  },
  proxy: 'http://localhost:7777', // see https://github.com/request/request#proxies
  requestOpts: { // see https://github.com/request/request#requestoptions-callback
    timeout: 10000
  },
  logger: function(message) {
 
  },
  progressCb: function(totalLength, progressLength, chunkLength) {
 
  }
}, function(){});
```

Also same problem when I run gulp task:

```
gulp.task('selenium', function (done) {
  selenium.install({
    drivers: {
      chrome: {},
    },
    logger: function (message) {}
  }, function (err) {
    if (err) return done(err);

    selenium.start(function (err, child) {
      if (err) return done(err);
      selenium.child = child;
      done();
    });
  });
});
```

i get error:
```
Error: Missing C:\Source\humbakTestyAutomatyczne\ux2\investmentfunds\InvestmentFunds.Web\node_modules\selenium-standalone\.selenium\edg
edriver\15063-MicrosoftEdgeDriver.exe
    at C:\Source\humbakTestyAutomatyczne\ux2\investmentfunds\InvestmentFunds.Web\node_modules\selenium-standalone\lib\check-paths-existence.js:15:
20
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
```
Why it looking for edge driver if I only wants chrome?

## Log

```
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.3/selenium-server-standalone-3.3.1.jar
to: C:\Users\lb23560\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\selenium-server\3.3.1-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.28/chromedriver_win32.zip
to: C:\Users\lb23560\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\chromedriver\2.28-x64-chromedriver
---
ie install:
from: https://selenium-release.storage.googleapis.com/3.0/IEDriverServer_x64_3.0.0.zip
to: C:\Users\lb23560\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\iedriver\3.0.0-x64-IEDriverServer.exe
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-win64.zip
to: C:\Users\lb23560\AppData\Roaming\npm\node_modules\selenium-standalone\.selenium\geckodriver\0.15.0-x64-geckodriver
---
File from https://selenium-release.storage.googleapis.com/3.0/IEDriverServer_x64_3.0.0.zip has already been downloaded
C:\Users\lb23560\AppData\Roaming\npm\node_modules\selenium-standalone\bin\selenium-standalone:107
        throw err;
        ^

Error: Could not download https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-win64.zip: Error: unable to verify
the first certificate
    at Request.<anonymous> (C:\Users\lb23560\AppData\Roaming\npm\node_modules\selenium-standalone\lib\install.js:289:12)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (C:\Users\lb23560\AppData\Roaming\npm\node_modules\selenium-standalone\node_modules\request\request.js:845:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
```

## Your Environment
Windows 7 .
packag.json 
```
"devDependencies": {
    "allure-commandline": "^2.3.5",
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-register": "^6.26.0",
    "cross-env": "^5.0.5",
    "eslint": "^4.9.0",
    "mocha": "^4.0.1",
    "mocha-allure-reporter": "^1.3.2",
    "npm-run-all": "^4.1.1",
    "rimraf": "^2.6.2",
    "selenium-standalone": "^6.11.0",
    "webdriverio": "^4.8.0"
  }
```

**Comment by vvo** [comment]
closed by #448
