### ISSUE TITLE
With v6.13.0, browserName phantomjs now tries to load with chrome driver and fails

### ISSUE THREAD

**Issue by jlchereau** [vvo/selenium-standalone#349]
## Expected Behavior
Tests should work as with previous versions, including v6.12.0

```
[18:16:27]  COMMAND	POST 	 "/wd/hub/session"
[18:16:27]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"phantomjs","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.11.0","name":"webdriverio"}}}
[18:16:30]  INFO	SET SESSION ID 556db330-1bea-11e8-9d15-3bc237a2f612
[18:16:30]  RESULT		{"applicationCacheEnabled":false,"rotatable":false,"handlesAlerts":false,"databaseEnabled":false,"version":"2.1.1","platform":"linux-unknown-64bit","browserConnectionEnabled":false,"proxy":{"proxyType":"DIRECT"},"nativeEvents":true,"acceptSslCerts":false,"driverVersion":"1.2.0","locationContextEnabled":false,"webStorageEnabled":false,"browserName":"phantomjs","takesScreenshot":true,"driverName":"ghostdriver","javascriptEnabled":true,"cssSelectorsEnabled":true}
```
Full logs at https://travis-ci.org/Memba/Memba-Blog/jobs/346903996

## Current Behavior and Logs
```
[09:22:28]  COMMAND	POST 	 "/wd/hub/session"
[09:22:28]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"phantomjs","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.12.0","name":"webdriverio"}}}
ERROR: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.14.12-041412-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.12 seconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'travis-job-memba-memba-blog-352740868', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.12-041412-generic', java.version: '1.8.0_151'
Driver info: driver.version: unknown
phantomjs
    at new RuntimeError (/home/travis/build/Memba/Memba-Blog/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/home/travis/build/Memba/Memba-Blog/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
    at Request.self.callback (/home/travis/build/Memba/Memba-Blog/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:421:20)
    at Request.<anonymous> (/home/travis/build/Memba/Memba-Blog/node_modules/webdriverio/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:421:20)
    at IncomingMessage.<anonymous> (/home/travis/build/Memba/Memba-Blog/node_modules/webdriverio/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
```

Full log at https://travis-ci.org/Memba/Memba-Blog/jobs/352740868
Config at https://github.com/Memba/Memba-Blog/blob/master/wdio.conf.js

## Steps to Reproduce
Run tests with https://github.com/Memba/Memba-Blog

## Your Environment
* Version of `selenium-standalone` that you are using: v6.13.0
* Is there another tool calling `selenium-standalone` on your behalf:
* System/platform: Travis-CI
* Other details that might be important: was working with wdio-selenium-standalone-service v0.0.9 and selenium-standalone v6.12.0.

**Comment by vvo** [comment]
@vasikarla @WillBrock can you help maybe?

**Comment by WillBrock** [comment]
I'm not too familiar with phantomjs but the changes from 6.13 would only get hit if the driver is chrome.

@jlchereau to rule some things out, have you tried running selenium-standalone without using the webdriverio selenium standalone service?

**Comment by jlchereau** [comment]
@WillBrock, I have only been using the webdriverio selenium standalone service.
