### ISSUE TITLE
No Firefox driver exists

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#352]
Your latest version does not seem to have the Firefox driver:

```
ERROR: connection refused
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'M3.local', ip: '10.0.202.101', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_92'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:        0x10d07149e - backtrace::backtrace::trace::h3ab5720c483fe461
   1:        0x10d0714dc - backtrace::capture::Backtrace::new::h096accf58447e0d5
   2:        0x10cfaa534 - webdriver::error::WebDriverError::new::hc0958d01acda7bfc
   3:        0x10cfb1300 - geckodriver::marionette::MarionetteHandler::create_connection::h59a68c8dfef48e54
   4:        0x10cf90d3c - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::h5a26ba0bb4fdb139
   5:        0x10cf690c5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f868f7a1a12bdcc
   6:        0x10cf73d2d - std::panicking::try::do_call::hfce1ad2a948c3632
   7:        0x10d11da5c - __rust_maybe_catch_panic
   8:        0x10cf86eb5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h651dedb755194a8c
   9:        0x10d119c4b - std::sys::imp::thread::Thread::new::thread_start::h48c72bb09587cbc3
  10:     0x7fff602256c0 - _pthread_body
  11:     0x7fff6022556c - _pthread_start
firefox
    at new RuntimeError (/Users/michael-heuberger/code/something/legacy/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/michael-heuberger/code/something/legacy/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
    at Request.self.callback (/Users/michael-heuberger/code/something/legacy/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/michael-heuberger/code/something/legacy/node_modules/webdriverio/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/michael-heuberger/code/something/legacy/node_modules/webdriverio/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by binarykitchen** [comment]
When I run `selenium-standalone install`, it doesn't install the Gecko driver. Hmmm, why?

**Comment by binarykitchen** [comment]
ah, I narrowed down the cause:

```
12:54:06.897 INFO - Capabilities {acceptInsecureCerts: true, browserName: firefox, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.12.0}, rotatable: true} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1522281246945	geckodriver	INFO	geckodriver 0.19.1
1522281246950	geckodriver	INFO	Listening on 127.0.0.1:23439
1522281247256	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-profile" "/var/folders/m7/r54_bcwj2ms2w5rpgdmvr6hh0000gn/T/rust_mozprofile.yX3PwhbLPYl0"
1522281248170	Marionette	INFO	Listening on port 2828
2018-03-29 12:54:09.493 plugin-container[8497:2961680] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x833b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

Why permission denied?

**Comment by vvo** [comment]
> Marionette	INFO	Listening on port 2828

Maybe this port is too low to be allowed? Did you look for permission denied marionette geckodriver issues?

**Comment by binarykitchen** [comment]
had to bump firefox to v59, then it worked. wish the error message was better.
