### ISSUE TITLE
seleniumVersion of 3.141.59 is not parsed  correctly due to 2-digit extension (59)

### ISSUE THREAD

**Issue by xywang68** [vvo/selenium-standalone#420]
## Expected Behavior
seleniumVersion of 3.141.59 should be parsed to 3.141
and the download from URL should be computed as:
from: http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar

## Current Behavior
seleniumVersion of 3.141.59 is parsed to 3.1419 (bug)
and the download from URL is computed as:
from: http://selenium-release.storage.googleapis.com/3.1419/selenium-server-standalone-3.141.59.jar

## Steps to Reproduce
1.  prepare a config file with selenium version as 3.141.59 and save to file system:
```
module.exports = {
  baseURL: 'http://selenium-release.storage.googleapis.com',
  version: '3.141.59',
  drivers: {
    chrome: {
      version: '2.45',
      arch: process.arch,
      baseURL: 'http://chromedriver.storage.googleapis.com'
    },
    ie: {
      version: '3.4.0',
      arch: process.arch,
      baseURL: 'http://selenium-release.storage.googleapis.com'
    },
    firefox: {
      version: '0.22.0',
      arch: process.arch,
      baseURL: 'http://github.com/mozilla/geckodriver/releases/download'
    },
    edge: {
      version: '10240',
      arch: process.arch,
      baseURL: 'http://download.microsoft.com/download/8/D/0/8D0D08CF-790D-4586-B726-C6469A9ED49C/MicrosoftWebDriver.exe'
    }
  }
};
```
2. run selenium-standalone install --config=<path_to_the_above_config_file>  

## Logs
```
vagrant@l1804Base:~/Run/AutoBDD$ selenium-standalone install --config=framework/configs/selenium-standalone_config.js -- -debug
----------
selenium-standalone installation starting
----------

---
selenium install:
from: http://selenium-release.storage.googleapis.com/3.1419/selenium-server-standalone-3.141.59.jar
to: /home/vagrant/Run/AutoBDD/node_modules/selenium-standalone/.selenium/selenium-server/3.141.59-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
to: /home/vagrant/Run/AutoBDD/node_modules/selenium-standalone/.selenium/chromedriver/2.45-x64-chromedriver
---
firefox install:
from: http://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
to: /home/vagrant/Run/AutoBDD/node_modules/selenium-standalone/.selenium/geckodriver/0.22.0-x64-geckodriver
/home/vagrant/Run/AutoBDD/node_modules/selenium-standalone/bin/selenium-standalone:111
        throw err;
        ^

Error: Could not download http://selenium-release.storage.googleapis.com/3.1419/selenium-server-standalone-3.141.59.jar
    at Request.<anonymous> (/home/vagrant/Run/AutoBDD/node_modules/selenium-standalone/lib/install.js:373:21)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/home/vagrant/Run/AutoBDD/node_modules/request/request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
```
## Your Environment
* Version of `selenium-standalone` that you are using: selenium-standalone@6.15.3
* Is there another tool calling `selenium-standalone` on your behalf: No
* System/platform: Ubuntu 18.04
* Other details that might be important: 
manually fixed in lib/compute-download-urls.js:46 by adding a '+' sign in the replace regex:

orig:
```
      opts.seleniumVersion.replace(/(\d+\.\d+)\.\d/, "$1"),
```
fix:
```
      opts.seleniumVersion.replace(/(\d+\.\d+)\.\d+/, "$1"),
```

**Comment by ablok** [comment]
Any idea when this fix will be released?

**Comment by caoxu2000** [comment]
@ablok why don't you just update it the code yourself rather than waiting for the release?

**Comment by dodo9396** [comment]
Has this been fixed? I'm facing the same issue.

**Comment by xywang68** [comment]
It has being fixed with the latest version.

**Comment by mkj28** [comment]
> It has being fixed with the latest version.

@xywang68 you mean it is fixed in https://github.com/vvo/selenium-standalone/releases/tag/v6.16.0 ?

**Comment by xywang68** [comment]
Yes

**Comment by mkj28** [comment]
Yeah, just found it - it was actually picked up by https://github.com/vvo/selenium-standalone/releases/tag/v6.15.5 and later
