### ISSUE TITLE
Mac OSX v6.20.0 chromiumedge driver install failure (self signed certificate error)

### ISSUE THREAD

**Issue by MHolmes91** [vvo/selenium-standalone#479]
## Expected Behavior
chromiumedge driver installs without issue. This works in v6.19.0

## Current Behavior
Could not request headers from https://msedgedriver.azureedge.net/86.0.600.0/edgedriver_mac64.zip: Error: self signed certificate in certificate chain. Running `curl Https://msedgedriver.azureedge.net/86.0.600.0/edgedriver_mac64.zip > test.zip` works.

## Steps to Reproduce

On Mac OSX:
1.  Connect to a VPN (I am using GlobalProtect)
3. `npm init` to create a new npm project
4. `npm i --save selenium-standalone` (should be v6.20.0)
5.  `node_modules/.bin/selenium-standalone install`

## Logs
```node_modules/.bin/selenium-standalone install
----------
selenium-standalone installation starting
----------
---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
to: node_modules/selenium-standalone/.selenium/selenium-server/3.141.59-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_mac64.zip
to: node_modules/selenium-standalone/.selenium/chromedriver/85.0.4183.87-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-macos.tar.gz
to: node_modules/selenium-standalone/.selenium/geckodriver/0.26.0-x64-geckodriver
---
chromiumedge install:
from: https://msedgedriver.azureedge.net/86.0.600.0/edgedriver_mac64.zip
to: node_modules/selenium-standalone/.selenium/chromiumedgedriver/86.0.600.0-x64-msedgedriver
node_modules/selenium-standalone/bin/selenium-standalone:119
    throw err;
    ^
Error: Could not request headers from https://msedgedriver.azureedge.net/86.0.600.0/edgedriver_mac64.zip: Error: self signed certificate in certificate chain
  at Request.<anonymous> (node_modules/selenium-standalone/lib/install.js:567:8)
  at Object.onceWrapper (events.js:273:13)
  at Request.emit (events.js:182:13)
  at Request.onRequestError (node_modules/request/request.js:877:8)
  at ClientRequest.emit (events.js:182:13)
  at TLSSocket.socketErrorListener (_http_client.js:399:9)
  at TLSSocket.emit (events.js:182:13)
  at emitErrorNT (internal/streams/destroy.js:82:8)
  at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
  at process.internalTickCallback (internal/process/next_tick.js:72:19)
LAMU02CP06UPWD7:e2e agarg59$
```

## Your Environment
* Version of `selenium-standalone` that you are using: v6.20.0
* Is there another tool calling `selenium-standalone` on your behalf: No
* System/platform: Mac OS X 10.15.5
* Other details that might be important:

**Comment by mgrybyk** [comment]
Can you try without VPN?
