### ISSUE TITLE
Selenium-standalone tries to install non-existent edgedriver version for linux

### ISSUE THREAD

**Issue by L0tso** [vvo/selenium-standalone#516]
## Current Behavior
I am using Selenium-standalone as part of my wdio tests. Selenium-standalone tries to installl non-existent edgedriver version for linux from https://msedgedriver.azureedge.net/87.0.664.47/edgedriver_linux64.zip

package-json
```    "@wdio/cli": "^6.10.2",
    "@wdio/local-runner": "^6.10.2",
    "@wdio/mocha-framework": "^6.0.12",
    "@wdio/selenium-standalone-service": "^6.10.3",
    "@wdio/spec-reporter": "^6.8.1",
    "@wdio/sync": "^6.10.0",
    "selenium-standalone": "^6.22.1"
```
wdio-config: 
```
exports.config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    logLevel: 'error',
    bail: 0,

    baseUrl: 'http://localhost',
    waitforTimeout: 10000,

    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [[
    'selenium-standalone', {
      drivers: {chrome: 'latest'},
      skipSeleniumInstall: false
    }]],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
}

```

## Logs 
```
HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/home/user/test/wd-bug-1/node_modules/got/dist/source/core/index.js:896:31)
    at Request._onResponse (/home/user/test/wd-bug-1/node_modules/got/dist/source/core/index.js:931:24)
    at ClientRequest.<anonymous> (/home/user/test/wd-bug-1/node_modules/got/dist/source/core/index.js:945:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.origin.emit (/home/user/test/wd-bug-1/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22) {
  code: undefined,
  timings: {
    start: 1606726360145,
    socket: 1606726360146,
    lookup: 1606726360327,
    connect: 1606726360390,
    secureConnect: 1606726360562,
    upload: 1606726360562,
    response: 1606726360817,
    end: 1606726360818,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 181,
      tcp: 63,
      tls: 172,
      request: 0,
      firstByte: 255,
      download: 1,
      total: 673
    }
  }
}
```

## Your Environment
* Version of `selenium-standalone` that you are using: 6.22.1
* Is there another tool calling `selenium-standalone` on your behalf: wdio
* System/platform: ubuntu

**Comment by mgrybyk** [comment]
Undesired browser download will be fixed with https://github.com/webdriverio/webdriverio/pull/6176

To workaround it temporary add chromiumedge: false

**Comment by L0tso** [comment]
@mgrybyk Great!
But in case I need the latest chromiumedge version for Linux, it will throw an error.

**Comment by mgrybyk** [comment]
yeah, because it doesn't exist
