### ISSUE TITLE
selenium-standalone start Not working in Ubuntu 12.4LTS

### ISSUE THREAD

**Issue by byteshiva** [vvo/selenium-standalone#65]
I'm getting this error when installed in ubuntu 
```
 uname -a
Linux siva-HP-Mini-110-1100 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:12 UTC 2014 i686 i686 i686 GNU/Linux
```

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

```

**Comment by vvo** [comment]
Do you have Java installed?

Did you do this:
- selenium-standalone install
- selenium-standalone start

?

**Comment by byteshiva** [comment]
I did   ``` $ selenium-standalone install && selenium-standalone start ```

let me check if the system has java installed and get back to you.

**Comment by byteshiva** [comment]
It worked after following the below steps to install java8
```
$ sudo add-apt-repository ppa:webupd8team/java
$ sudo apt-get update
$ sudo apt-get install oracle-java8-installer

$ sudo apt-get install oracle-java8-set-default

```

**Comment by vvo** [comment]
Ok thanks a lot
