### ISSUE TITLE
error when installing version 2.45

### ISSUE THREAD

**Issue by tnguyen14** [vvo/selenium-standalone#74]
I tried to install version 2.45 (to fix this issue https://code.google.com/p/selenium/issues/detail?id=8088), and got the following error:

```
❯ selenium-standalone install --version 2.45
----------
selenium-standalone installation starting
----------


/usr/local/lib/node_modules/selenium-standalone/lib/compute-download-urls.js:14
eleniumVersion = opts.seleniumVersion.slice(0, opts.seleniumVersion.lastIndexO
                                                                    ^
TypeError: Object 2.45 has no method 'lastIndexOf'
    at computeDownloadUrls (/usr/local/lib/node_modules/selenium-standalone/lib/compute-download-urls.js:14:81)
    at Object.install (/usr/local/lib/node_modules/selenium-standalone/lib/install.js:50:14)
    at Object.actions.install (/usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:79:14)
    at javaFound (/usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone:42:18)
    at /usr/local/lib/node_modules/selenium-standalone/node_modules/whereis/index.js:28:14
    at ChildProcess.exithandler (child_process.js:645:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
```

**Comment by vvo** [comment]
$ selenium-standalone install --version 2.45.0

should work

**Comment by tnguyen14** [comment]
Oh silly me! It does. Thanks for that.
