### ISSUE TITLE
Error: Could not download http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar

### ISSUE THREAD

**Issue by michael-benin-CN** [vvo/selenium-standalone#8]
```
Error: Could not download http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
at ClientRequest.<anonymous> (/Users/mbenin/projects/copilot/node_modules/selenium-standalone/install.js:100:21)
at ClientRequest.g (events.js:180:16)
at ClientRequest.EventEmitter.emit (events.js:95:17)
at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
at Socket.socketOnData [as ondata] (http.js:1583:20)
at TCP.onread (net.js:527:27)
```

https://github.com/webdriverjs/grunt-webdriver/issues/29

**Comment by clubajax** [comment]
I'm having this problem because the googleapis domain is blocked.

My question is, does this have to download selenium-server-standalone-2.45.0.jar every time it is run? I used my phone as a hotspot and downloaded the file... when I hooked back up to my company network, it wanted to download the file again.

**Comment by vvo** [comment]
latest selenium standalone will not redownload every time run/installed
