### ISSUE TITLE
TypeError: Cannot call method 'on' of null

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#86]
```
/home/michael-heuberger/Development/xxx/node_modules/selenium-standalone/lib/start.js:64
    selenium.stdout.on('data', noop);
                    ^
TypeError: Cannot call method 'on' of null
  at /home/michael-heuberger/Development/xxx/node_modules/selenium-standalone/lib/start.js:64:21
  at /home/michael-heuberger/Development/xxx/node_modules/async/lib/async.js:254:17
  at done (/home/michael-heuberger/Development/xxx/node_modules/async/lib/async.js:135:19)
...
```

**Comment by vvo** [comment]
Fixed in 4.2.2
